### ISSUE TITLE
Cython missing as a build dependency

### ISSUE THREAD

**Issue by p-j-smith** [KCL-BMEIS/ExeTera#232]
Hi, thanks for making ExeTera, it seems like a very cool project!

I just tried to install ExeTera in a new environment with:

```
python -m pip install -e .
```

But I got the following error:

```
Obtaining file:///Users/paul/github/ExeTera
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/Caskroom/miniconda/base/envs/exetera/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/paul/github/ExeTera/setup.py'"'"'; __file__='"'"'/Users/paul/github/ExeTera/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3x/026zvn0n35v9cg_b27xv40vm0000gn/T/pip-pip-egg-info-ecyeds8a
       cwd: /Users/paul/github/ExeTera/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/paul/github/ExeTera/setup.py", line 3, in <module>
      from Cython.Build import cythonize
  ModuleNotFoundError: No module named 'Cython'
  ----------------------------------------
WARNING: Discarding file:///Users/paul/github/ExeTera. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is because `Cython.build.cythonize` is used in the `setup.py`.  You can add a `pyproject.toml` file to specify Cython as a steup dependency:

```
[build-system]
requires = ["setuptools", "wheel", "Cython"]
```

**Comment by atbenmurray** [comment]
Thank you for raising this with us! Cython is a new dependency for the project and it looks like we don't have it quite right yet. It looks like your suggestion should do the trick.
